#include<iostream>
int main(){
    //Pseudo-Random number generators (PRNGs) are algorithms that use mathematical formulas or pre-calculated tables to produce sequences of numbers that appear random. They are called "pseudo" because the numbers are not truly random; they are determined by an initial value known as a seed. The sequence of numbers generated by a PRNG is entirely determined by the seed value, and if the same seed is used, the same sequence of numbers will be produced.
    srand(time(NULL)); // Seed the random number generator with the current time
    for(int i=0;i<10;i++){
        int randomNum = rand() % 100; // Generate a random number between 0 and 99
        std::cout << randomNum << std::endl;
    }
    return 0;
}